project:
  type: website
  output-dir: docs

website:
  title: "Kobe Kirk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - MP1.qmd
      - MP3.qmd

format:
  html:
    theme:
      - Lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

